name: Python package
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y python-openssl
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        python_version: '3.8.0'
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
